# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Sh

on:
  push:
    paths:
      - "**.sh"
      - "Makefile"
      - ".github/workflows/sh.yml"
  pull_request:
    paths:
      - "**.sh"
      - "Makefile"
      - ".github/workflows/sh.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rnn lint-sh (via shellcheck)
        run: make lint-sh
